language: node_js
node_js:
  - "10"
  - node
cache: yarn

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
